branch-defaults:
  master:
    environment: docker-ner-node-dev
    group_suffix: null
global:
  application_name: docker-ner-node
  branch: null
  default_ec2_keyname: aequor-neptune-useast1
  default_platform: Docker 17.03.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
